### ISSUE TITLE
error

### ISSUE THREAD

**Issue by biskfather** [Void-Developments/void_parking#1]
[ script:void_parking] SCRIPT ERROR: @void_parking/server/sv_main.lua:176: void_parking was unable to execute a query!
[ script:void_parking] Table 'qbcoreframework_6db759.parkingmeters' doesn't exist
[ script:void_parking] SELECT * FROM parkingmeters []
[ script:void_parking] > handler (@void_parking/server/sv_main.lua:176)
[ script:void_parking] > <unknown> (@oxmysql/dist/build.js:21832)
[ script:void_parking] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by biskfather** [comment]
also ive executed the sql it comes with but it doesnt create a table called parkingmeters

**Comment by darkets** [comment]
Rerun the sql file now. Sorry for the late response
